# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-c18d26ba-ac6c-445e-b77d-f8d347eaf07a";
    fsType = "btrfs";
  };

  boot.initrd.luks.devices."luks-c18d26ba-ac6c-445e-b77d-f8d347eaf07a".device =
    "/dev/disk/by-uuid/c18d26ba-ac6c-445e-b77d-f8d347eaf07a";

  fileSystems."/home" = {
    device = "/dev/mapper/luks-c18d26ba-ac6c-445e-b77d-f8d347eaf07a";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/luks-c18d26ba-ac6c-445e-b77d-f8d347eaf07a";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/9D5E-7C36";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/318f3cf7-e505-457e-abd7-b57775b5b783"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
